discovery_sidebar_enabled:
  default: false
  client: true

discovery_sidebar_content:
  default: |
    ### I'm a sidebar!

    This is important information.
  type: string
  textarea: true
  client: true

discovery_sidebar_footer_enabled:
  default: false
  client: true

discovery_sidebar_recents_enabled:
  default: false
  client: true
