discovery_sidebar_enabled:
  default: true
  client: true

discovery_sidebar_content:
  default: |
    ### I'm a sidebar!

    This is here to let you know that MSJ is gay.

    That is all.

    Carry on.
  type: textarea
  client: true

discovery_sidebar_footer_enabled:
  default: true
  client: true
